[build]
command = "npm run build"
publish = "dist"

[[edge_functions]]
directory = ".netlify/functions"
path = "/api/orders"
function = "create-order"

[[edge_functions]]
directory = ".netlify/functions"
path = "/api/orders/:orderID/capture"
function = "capture-order"