[build]
functions = ".netlify/functions"
command = "npm run build"
publish = "dist"

[[edge_functions]]
path = "/api/orders"
function = "create-order"

[[edge_functions]]
path = "/api/orders/:orderID/capture"
function = "capture-order"